import Head from "next/head";
import items from "./api/items.json";
import Wallet from "../components/Wallet";

import React, { useState, useEffect } from "react";

//Constants
const TWITTER_HANDLE = "_buildspace";
const TWITTER_LINK = `https://twitter.com/${TWITTER_HANDLE}`;

export default function App() {
    return (
        <div className="container">
            <Head>
                <title>Buildspace IPFS Beam-Up</title>
                <meta name="description" content="Generated by @_buildspace" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Wallet />
            </main>

            <footer>
                <a href="https://twitter.com/_buildspace">
                    <img src="twitter-logo.svg" className="footer-img" />
                </a>
                <p className="footer-text">built on @_buildspace</p>
            </footer>
        </div>
    );
}
